### ISSUE TITLE
Update to 23.08 runtime

### ISSUE THREAD

**Issue by zecakeh** [flathub/org.freedesktop.Sdk.Extension.rust-nightly#1021]
For [Fractal](https://gitlab.gnome.org/GNOME/fractal), we rely on nightly Rust in CI to generate docs, because we use unstable flags.

Since the GNOME nightly runtime is now based on the 23.08 freedesktop.org runtime, we need this extension to be branched too.

**Comment by hfiguiere** [comment]
just pushed the branch. give it a few hours.
