### ISSUE TITLE
Rework Rust Stable and Nightly Flathub Configurations to be Consistent in General Format

### ISSUE THREAD

**Issue by da2ce7** [flathub/org.freedesktop.Sdk.Extension.rust-nightly#1261]
The nightly (this repo): https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-nightly ,
and stable: https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-stable are quite different.

Unifiy and rework both repos to have the best-standard way of building and updating the flathub package.

The only differences should be the changes needed to specify the nightly and stable variants, and the time-based update scheduler for the nightly version.

**Comment by bbhtt** [comment]
What changes do you specifically mean?

This specifically uses extra data because we don't want it to be built on Flathub infra as we don't allow Nightly packages.

**Comment by da2ce7** [comment]
For example, using the 'rust` ` x-checker-data`, like the stable version, instead of the rotating url.

**Comment by bbhtt** [comment]
Rust x checker does not support extra data sources.

**Comment by da2ce7** [comment]
One of the motivations for this change is that the rotating url seems not to be updating the `https://static.rust-lang.org/dist/*` packages... they are stuck on the date: `2024-05-14`, while the mold and rust-analyzer are being updated on schedule as expected.

**Comment by bbhtt** [comment]
It needs to be manually updated then, looks like the rotating-url needs a link with the latest release as the `url` parameter, but there is no such URL offered.

**Comment by bbhtt** [comment]
Updated it.

**Comment by bbhtt** [comment]
Jfyi, I added a custom workflow and rust modules will be getting updated once weekly.
