### ISSUE TITLE
use the `FLATPAK_ENABLE_SDK_EXT` to enable rust-nightly for development in vscode or vscodium

### ISSUE THREAD

**Issue by da2ce7** [flathub/org.freedesktop.Sdk.Extension.rust-nightly#1262]
In the previous version of rust nightly, and with current versions of rust stable, it was possible to include `rust-nightly` in the `FLATPAK_ENABLE_SDK_EXT` environmental variable to enable this software development kit in an development environment.

However this dose not work with the new version of this package.

I would like to this feature as I often need to check an nightly version of rust to check future comparability in my development of other packages.

I comprehend not to use the nightly SDK in deployment for flathub otherwise in for distribution purposes.  However for development purposes I would expect using a (regularly updated, but not necessarily nightly) is quire within scope of this package.

**Comment by bbhtt** [comment]
That environment variable comes from flatpak ide wrapper https://github.com/flathub-infra/ide-flatpak-wrapper

Looks like it depends on the path being `/use/lib/sdk` 

https://github.com/flathub-infra/ide-flatpak-wrapper/blob/3314b55ccd4ece8810715787e246f8407e20caab/vscode.sh#L61

You should open an issue there so that extensions using extra data are supported too

**Comment by bbhtt** [comment]
The current path used by this is document in the readme https://github.com/flathub/org.freedesktop.sdk.extension.rust-nightly?tab=readme-ov-file#usage

**Comment by bbhtt** [comment]
Looks like all it does is set PATH, so you can just launch your editor with 

```
flatpak run --env=PATH=/usr/lib/sdk/rust-nightly/extra/sdk/rust-nightly/bin:/app/bin:/usr/bin com.visualstudio.code
```

**Comment by da2ce7** [comment]
> That environment variable comes from flatpak ide wrapper https://github.com/flathub-infra/ide-flatpak-wrapper
> 
> Looks like it depends on the path being `/use/lib/sdk`
> 
> https://github.com/flathub-infra/ide-flatpak-wrapper/blob/3314b55ccd4ece8810715787e246f8407e20caab/vscode.sh#L61
> 
> You should open an issue there so that extensions using extra data are supported too

We could include a `enable.sh`, as the other package uses, but updated to point to the extra folder:
https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-stable/blob/branch/23.08/org.freedesktop.Sdk.Extension.rust-stable.json#L250-L265

**Comment by bbhtt** [comment]
It works without enable.sh to; if it doesn't look in the `extra` subfolder it can't find enable.sh anyways.

**Comment by bbhtt** [comment]
This should work now, the old path was restored in the extension through symlinks
