### ISSUE TITLE
Build for org.freedesktop.Sdk//22.08beta

### ISSUE THREAD

**Issue by zecakeh** [flathub/org.freedesktop.Sdk.Extension.rust-nightly#615]
Hi, we're using nightly Rust to generate our docs in [Fractal's CI](https://gitlab.gnome.org/GNOME/fractal/-/blob/main/.gitlab-ci.yml#L139), but since it's not available for the `22.08beta` runtime, our CI fails.

Would it kindly be possible to add this to flathub-beta?

**Comment by bilelmoussaoui** [comment]
Should be fixed once the build is published
